#!/sbin/busybox sh

export BOOTREC_CACHE_NODE="/dev/block/mmcblk0p13 b 179 13"
export BOOTREC_CACHE="/dev/block/mmcblk0p13"
export BOOTREC_EVENT_NODE="/dev/input/event0 c 13 64"
export BOOTREC_EVENT="/dev/input/event0"
export BOOTREC_LED_RED="/sys/class/leds/led_7-rgb1-red/brightness"
export BOOTREC_LED_GREEN="/sys/class/leds/led_8-rgb2-green/brightness"
export BOOTREC_LED_BLUE="/sys/class/leds/led_9-rgb3-blue/brightness"
