#!/sbin/busybox sh

export BOOTREC_CACHE_NODE="/dev/block/mmcblk0p13 b 179 13"
export BOOTREC_CACHE="/dev/block/mmcblk0p13"
export BOOTREC_EVENT_NODE="/dev/input/event9 c 13 73"
export BOOTREC_EVENT="/dev/input/event9"
export BOOTREC_LED_RED="/sys/class/leds/pwr-red/brightness"
export BOOTREC_LED_GREEN="/sys/class/leds/pwr-green/brightness"
export BOOTREC_LED_BLUE="/sys/class/leds/pwr-blue/brightness"
